### ISSUE TITLE
Lets get rid of readline

### ISSUE THREAD

**Issue by Jelleas** [cs50/lib50#13]
This dependency is only used in one place, that's to ask for username in `_api.py`. This has been causing a headache for me as homebrew's readline recently upgraded to 8.0.0 and doesn't seem to cooperate with Python.

**Comment by dmalan** [comment]
What's the alternative? I think we used this to prepopulate username? Without it, we could do something like

```
Username [lastusernamehere]: 
```

though I think we've assumed many folks won't know that `[]` means default?

**Comment by crossroads1112** [comment]
This feature is no longer used in v3. We only ever prefilled if students happened to have run `git config --global submit50.https://github.com/submit50.username <username>` which we needed for SSH authentication. We don't do this anymore.
