### ISSUE TITLE
add support for ".cs50.yml"

### ISSUE THREAD

**Issue by dmalan** [cs50/lib50#15]
And can we throw an exception if both `.cs50.yml` and `.cs50.yaml` are found so that a tool can advise a user to remove one? Am thinking that might be clearer than prioritizing one over the other?

**Comment by Jelleas** [comment]
Support for `.yml` is there now. However, raising an error in case both `.yml` and `.yaml` exists brings with it some additional cost when running a tool remotely. We would have to send two requests to GitHub to decide whether to raise an error. In case we just prefer one format over the other (but support both), we would end up only sending a single request to GitHub in case the preferred format is used.

Question being, is the error worth an additional request? Or should we instead document our preferred format and pick that one if we find it?

**Comment by dmalan** [comment]
Much as I love sticking to standards, the only place in the world I've seen `.yaml` used is in the spec. Everyone else seems to use `.yml`. I'd be okay with just supporting the latter, fwiw, and ignoring the former altogether.

**Comment by crossroads1112** [comment]
We do two requests now and advise the user to remove one now.
