### ISSUE TITLE
Raise some exception other than InvalidSlugError when GitHub itself seems to be down

### ISSUE THREAD

**Issue by dmalan** [cs50/lib50#17]
Probably in https://github.com/cs50/lib50/blob/master/lib50/_api.py?

**Comment by Jelleas** [comment]
https://github.com/cs50/lib50/blob/19c48889523a8ea8a2ad98e567ecb55a9d1400c6/lib50/_api.py#L671-L680

In `lib50` (in contrast to check50/submit50 v2) we raise `Error(_("Could not connect to GitHub."))` upon receiving any statuscode other than 404 from GitHub. But this is not ideal given that GitHub might 404 when they experience outage.

To improve on this I just opened https://github.com/cs50/lib50/pull/18. This pings https://www.githubstatus.com/api after any non-404 response, and after both requests for (`.cs50.yml` and `.cs50.yaml`) returned with 404.

**Comment by dmalan** [comment]
Awesome, thanks!
