### ISSUE TITLE
Strange password prompt behavior

### ISSUE THREAD

**Issue by dimasahmad** [cs50/lib50#39]
Password prompt in [lib50 2.1.0+a5104c1](https://github.com/cs50/lib50/tree/a5104c1ccb732d5c1e4a252a40265e2b08350ce3) does not handle some special key correctly.

I'm testing using CS50 sandbox, and here's `cat /etc/os-release`:

```bash
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
```

Running the [submit50 3.0.3+70002d6](https://github.com/cs50/submit50/tree/70002d6825fec3a0e4428b71999a64a4b20d6e5b) command with verbose argument:

```bash
submit50 cs50/problems/2019/fall/hello -v
Connecting...
Authenticating...
INFO:lib50._api:git -c credential.helper= -c 'credential.helper=cache --socket /root/.git-credential-cache/lib50' credential fill
GitHub username: siswa50
GitHub password: 
```

If backspace is pressed when the password is empty:

```bash
GitHub password: Sorry, something's wrong! Let sysadmins@cs50.harvard.edu know!
Traceback (most recent call last):
  File "/usr/local/bin/submit50", line 11, in <module>
    load_entry_point('submit50', 'console_scripts', 'submit50')()
  File "/root/sandbox/submit50/submit50/__main__.py", line 147, in main
    user_name, commit_hash, message = lib50.push("submit50", args.slug, CONFIG_LOADER, prompt=prompt)
  File "/root/sandbox/lib50/lib50/_api.py", line 79, in push
    with authenticate(remote["org"], repo=repo) as user, prepare(tool, slug, user, included):
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/root/sandbox/lib50/lib50/_api.py", line 282, in authenticate
    with _authenticate_https(org, repo=repo) as user:
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/root/sandbox/lib50/lib50/_api.py", line 955, in _authenticate_https
    password = _prompt_password(_("GitHub password: "))
  File "/root/sandbox/lib50/lib50/_api.py", line 1040, in _prompt_password
    password.pop()
IndexError: pop from empty list
Submission cancelled.
```

While the following are not a fatal error, it slightly annoying as the prompt can't handle some characters and just printing asterisks everytime these button pressed, like when pressing `delete` button, and it can be deleted by pressing `backspace`:

```bash
GitHub password: ****
```

Here's another that I've found so far:
* Pressing `tab`, `esc` will add one asterisk
* Pressing arrow keys, `F1`-`F4`, `home`, `end` will add three asterisks
* Pressing `delete`, `insert`, `pageup`, `pagedown` will add four asterisks
* Pressing `F5`-`F12` will add five asterisks

**Comment by crossroads1112** [comment]
The backspace on empty password bit is an easy fix (fixed here ff3ebee831c7e0e46577c2370759a9de06e24bd9), but the other stuff is less so. What your program receives when you type e.g. "F1" is entirely dependent on your terminal. It's not easy to write code that conforms to these standards and is also cross platform. A few cursory Google searches didn't reveal any good standalone libraries that do this. NCurses seems to, but we couldn't use Python's native `curses` module since it's not available on Windows, and it seems like huge overkill for what we ultimately want to do.
