### ISSUE TITLE
how best to load keys for multiple tools in a given .cs50.yaml file?

### ISSUE THREAD

**Issue by dmalan** [cs50/lib50#6]
Re https://github.com/cs50/lib50/blob/develop/lib50/config.py, best for caller to call `load` 
twice?

**Comment by Jelleas** [comment]
What's the usecase here? A tool that needs to inspect multiple other tools settings?

But yes, calling `load()` twice is probably the best option Small price to pay is parsing .yaml twice (from memory, not disk), no other work is duplicated. This way you get all the tool agnostic error handling that `lib50` can do for you.

**Comment by dmalan** [comment]
Yeah, both lab50 and submit.cs50.io need to peek at `check50`'s key.
