### ISSUE TITLE
any reason not to use --branch and --single-branch when cloning?

### ISSUE THREAD

**Issue by kzidane** [cs50/lib50#62]
To speed up the cloning process? https://github.com/cs50/lib50/blob/develop/lib50/_api.py#L456

**Comment by rongxin-liu** [comment]
So passing --single-branch will work and require minimum code changes (if no branch is specified, the master branch will be fetched). Passing --branch {branch} will fail if the branch does not exist.

I guess in our case, if the goal is to speed up the cloning process, alternatively, perhaps we can always fetch an empty branch (e.g., the master/main branch which we seldom used for pset submission). Or use --single-branch to let it fetch whatever default branch the repo specifies.

**Comment by kzidane** [comment]
#63
