### ISSUE TITLE
fetch depth 1 for local()

### ISSUE THREAD

**Issue by Jelleas** [cs50/lib50#64]
On a related note to https://github.com/cs50/lib50/issues/62 and https://github.com/cs50/lib50/pull/63,  should `lib50` fetch with `--depth 1` for `local()`? That would make it much less punishing if someone commits a large file to the checks by accident, then removes the file, but without removing the commit from git. This came up in a conversation recently about adding reasonably large data files to checks. 

Relevant snippet:

https://github.com/cs50/lib50/blob/ca41d702421250781663c3326f616be74e4e4981/lib50/_api.py#L144

Here's an incredibly detailed explanation on how to keep a shallow clone up to date with fetch (again with `--depth 1`):

https://stackoverflow.com/questions/41075972/how-to-update-a-git-shallow-clone/41081908#41081908

**Comment by Jelleas** [comment]
@kzidane @rongxin-liu (no rush, just figured you might miss it otherwise ;)

**Comment by kzidane** [comment]
Yeah, that sounds like a good idea. Wanna add this to your PR, since it's kinda related, and test it, @rongxin-liu? Make sure the checks update correctly especially when `check50` is run twice, once with `--local` and once without per the SO post.

**Comment by kzidane** [comment]
#63
